name: adaptive-attack
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - ipython
  - ipykernel
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - tqdm
  - requests
  - pyyaml
  - regex
  - pip
  - six
  - sympy
  - tornado
  - ffmpeg
  - pytorch-cuda
  - torchaudio
  - pip:
      - absl-py==2.1.0
      - accelerate==0.32.1
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alpaca-eval==0.6.3
      - altair==5.3.0
      - annotated-types==0.7.0
      - anthropic==0.30.1
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - chardet==5.2.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.30.0
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==2.20.0
      - deepspeed==0.14.4
      - dill==0.3.8
      - diskcache==5.6.3
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - email-validator==2.2.0
      - et-xmlfile==1.1.0
      - evaluate==0.4.2
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - fire==0.6.0
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fschat==0.2.36
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==3.40.0
      - gradio-client==1.1.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.25.2
      - huggingface-hub==0.23.4
      - importlib-resources==6.4.0
      - interegular==0.3.3
      - jiter==0.5.0
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lark==1.1.9
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lm-eval==0.4.3
      - lm-format-enforcer==0.10.1
      - lxml==5.2.2
      - markdown-it-py==2.2.0
      - markdown2==2.4.13
      - matplotlib==3.9.1
      - mbstrdecoder==1.1.3
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - more-itertools==10.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nh3==0.2.17
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numba==0.60.0
      - numexpr==2.10.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.36.0
      - openpyxl==3.1.5
      - orjson==3.10.6
      - outlines==0.0.46
      - pandas==2.2.2
      - pathvalidate==3.2.0
      - patsy==0.5.6
      - peft==0.12.0
      - pip==24.1.2
      - plotly==5.22.0
      - portalocker==2.10.0
      - prometheus-client==0.20.0
      - prometheus-fastapi-instrumentator==7.0.0
      - protobuf==5.27.2
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pybind11==2.13.1
      - pycountry==24.6.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydantic-settings==2.3.4
      - pydub==0.25.1
      - pyparsing==3.1.2
      - pytablewriter==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - ray==2.32.0
      - referencing==0.35.1
      - rich==13.7.1
      - rouge-score==0.1.2
      - rpds-py==0.19.0
      - ruff==0.5.1
      - sacrebleu==2.4.2
      - schedulefree==1.2.7
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - starlette==0.37.2
      - svgwrite==1.4.3
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - tenacity==8.5.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - timm==1.0.8
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.3.0
      - torchvision==0.18.0
      - tqdm-multiprocess==0.0.11
      - transformers==4.42.3
      - triton==2.3.0
      - trl==0.9.4
      - typepy==1.3.2
      - typer==0.12.3
      - tyro==0.8.5
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - ujson==5.10.0
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - vllm==0.5.1
      - vllm-flash-attn==2.5.9
      - wandb==0.17.7
      - watchfiles==0.22.0
      - wavedrom==2.0.3.post3
      - websockets==11.0.3
      - word2number==1.1
      - xformers==0.0.26.post1
      - xxhash==3.4.1
      - yarl==1.9.4
